version: '3.1'

services:
  todoapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - pgsql
  pgsql:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: todoapp
      POSTGRES_DB: todoapp