apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: todoapp
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  INIT_SCRIPT: |
    CREATE TABLE IF NOT EXISTS todos(
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL,
      completed BOOLEAN NOT NULL DEFAULT FALSE
    );