apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-back
  template:
    metadata:
      labels:
        app: todo-back
    spec:
      containers:
        - name: todo-back
          image: loadeksdee/todo-back:latest
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_URL
              value: postgres://postgres:postgres@postgres.default.svc.cluster.local:5432/todoapp
          imagePullPolicy: Always